ALTER TYPE "FeatureCode" ADD VALUE IF NOT EXISTS 'QR_MENU_VIEW';
ALTER TYPE "FeatureCode" ADD VALUE IF NOT EXISTS 'QR_ORDERING';
ALTER TYPE "FeatureCode" ADD VALUE IF NOT EXISTS 'ORDER_CANCELLATIONS';
ALTER TYPE "FeatureCode" ADD VALUE IF NOT EXISTS 'BILLING_RECEIPTS';
ALTER TYPE "FeatureCode" ADD VALUE IF NOT EXISTS 'WAITER_CALL_LOGS';
ALTER TYPE "FeatureCode" ADD VALUE IF NOT EXISTS 'SHOWCASE_RAILS';
ALTER TYPE "FeatureCode" ADD VALUE IF NOT EXISTS 'STAFF_PERFORMANCE';
ALTER TYPE "FeatureCode" ADD VALUE IF NOT EXISTS 'ONLINE_PAYMENT_IYZICO';
